# Set resistance table [toml] file path 'resistance_tbl = [{index = 0.0, value=0.0}]'
resistance_tbl_path = "/home/runner/Filesystemwatcherrust/src/setting/resistance_tbl.toml"
  
# Set specific heat table [toml] file path 'specific_heat_tbl = [{index = 0.0, value=0.0}]'
specific_heat_tbl_path = "/home/runner/Filesystemwatcherrust/src/setting/specific_heat_tbl.toml"
  
# Set heat transfer table [toml] file path 'heat_transfer_tbl = [{index = 0.0, value=0.0}]'
heat_transfer_tbl_path = "/home/runner/Filesystemwatcherrust/src/setting/heat_transfer_tbl.toml"

# Set current table [toml] file path 'current_tbl = [{index = 0.0, value=0.0}]'
current_tbl_path = "/home/runner/Filesystemwatcherrust/src/setting/current_tbl.toml"

# Set sample surface area [mm^2]
surface_area = 160.0

# Set sample weight [g]
weight = 10.0

# Set start sample temperature [K]
start_sample_temperature = 20.0

# Set enviroment temperature [K]
enviroment_temperature = 20.0

# Set pulse duration [ms]
pulse_duration = 15

# Set number of iterations
num_of_iterations = 1000
  
 # test
tbl_test = [ 
{temperature=11.11, specific_heat=22.22}, {temperature=66.11, specific_heat=99.22},
{temperature=55.1, specific_heat=88.2}
]
 