# Set watcher folder path 
 watcher_path = "/home/runner/Filesystemwatcherrust/src/test/" 
  
 # Set backup folder path 
 backup_path = "/home/runner/Filesystemwatcherrust/src/back/" 
  
 # Set log file path 
 logfile_path = "/home/runner/Filesystemwatcherrust/src/back/log.txt" 
  
 # Set compression level 0-NonCompression 
 compression_level = 0 
  
 # Set encryption password or comment this line for non encription 
 encryption_password = "pass" 
  
 # Set duration interval in [ms] 
 duration_interval = 100 
  
 # Set ignore list, this content will be ignored for backup. 
 ignore_list = ["aaa.txt", "daco.bar"]

 # test
tbl_test = [ 
{temperature=11.11, specific_heat=22.22}, {temperature=66.11, specific_heat=99.22},
{temperature=55.1, specific_heat=88.2}
]
 